/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Christopher Buck' at '4/14/17 9:41 PM' with Gradle 2.13
 *
 * @author Christopher Buck, @date 4/14/17 9:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
